# Generated by Django 4.2.9 on 2024-01-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_booking_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking", old_name="ID", new_name="Booking_ID",
        ),
        migrations.RenameField(model_name="menu", old_name="ID", new_name="Menu_ID",),
    ]
