# Generated by Django 4.2.9 on 2024-01-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_rename_id_booking_booking_id_rename_id_menu_menu_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="booking", name="Booking_ID",),
        migrations.RemoveField(model_name="menu", name="Menu_ID",),
    ]
