# Generated by Django 4.2.9 on 2024-01-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_remove_booking_booking_id_remove_menu_menu_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking", name="No_of_guests", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="menu", name="Inventory", field=models.IntegerField(),
        ),
    ]
