# Generated by Django 4.2.9 on 2024-01-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_alter_booking_no_of_guests_alter_menu_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="Booking_ID",
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="menu",
            name="Menu_ID",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
