# Generated by Django 4.2.9 on 2024-01-23 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0007_remove_booking_booking_id_remove_menu_menu_id"),
    ]

    operations = [
        migrations.DeleteModel(name="Booking",),
        migrations.DeleteModel(name="Menu",),
    ]
